### ISSUE TITLE
Missing import

### ISSUE THREAD

**Issue by wadael** [neo4j-product-examples/genai-workshop#28]
In the cell in § Some logics, I had to add an import "langchain_community" to solve an error when executing one cell after

So here's, my cell content

%pip install sentence_transformers langchain langchain-openai openai tiktoken python-dotenv gradio graphdatascience altair neo4j_tools
%pip install "vegafusion[embed]" langchain_community

**Comment by zach-blumenfeld** [comment]
#26 hoping this solves.  Thanks for pointing out!
